version: '3.9'
services:
  redis:
    image: redis:7-alpine
    container_name: dex-redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
volumes:
  redis-data: